### ISSUE TITLE
Stuck in step 2 - running catalog.sql

### ISSUE THREAD

**Issue by yin** [wscherphof/oracle-12c#22]
Hi,

I get always stuck at step2. The catalog.sql runs for hours:

    Tue Sep  15 08:38:22 UTC 2015
    Running catalog.sql...

If I press Ctrl+C to terminate the process the installation continues, but I think it might make problem while connecting to the DB.

The oracle process oracle_119_orcl takes ~2.0% of CPU, but while idle, it takes only 0-0.7% so I am not sure, where is the problem. Feel free to contact me for more info.

**Comment by totaskin** [comment]
I have the same issue. After step 1, I tried manually do the script and database asks username and password. Had no luck yet to provide correct user/pass.

**Comment by wscherphof** [comment]
I'm currently not using this repo actively myself. Who has time to look into it?

**Comment by jlafourc** [comment]
Hi,

I have the same issue. At the begining, I suspected the storage driver so I switched everything to BTRFS but it stays the same. 

Takes hours on my computer but @wscherphof says 15 mins. 

Julien

**Comment by jlafourc** [comment]
Hi,

I reply to myself. 

I tried again last night. I took a computer with a SSD intead of 5.4K HD. It appears to be faster (~23 mins). So I think Oracle needs good I/Os.

Julien

**Comment by yin** [comment]
@jlafourc Same here, works

**Comment by felixalvez** [comment]
I have a similar issue. I am on using SSD and waited for more than 2 hours i am still stuck. Last message i saw is Files created. I think it is stuck on startup nomount. Any ideas?
