### ISSUE TITLE
Step 2.3 fails - ORA-12547: TNS:lost contact

### ISSUE THREAD

**Issue by telegrapher** [wscherphof/oracle-12c#3]
I'm able to successfully run all the steps until I reach step 2.3.
The host OS is CentOS 7.

It seems that the first sqlplus command from /tmp/create is not able to connect to the database, which looks reasonable to me, since the script never starts the database.

This is the output I get when I run /tmp/create

root@c60e12683286 ~]# /tmp/create
Fri Jan 23 14:12:25 UTC 2015
Creating database...

SQL*Plus: Release 12.1.0.2.0 Production on Fri Jan 23 14:12:25 2015

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

ERROR:
ORA-12547: TNS:lost contact

SP2-0640: Not connected
SP2-0640: Not connected
SP2-0640: Not connected
SP2-0640: Not connected
SP2-0640: Not connected

Fri Jan 23 14:12:25 UTC 2015
Running catalog.sql...

**Comment by hellonico** [comment]
@telegrapher I ran into the same problem, and realized somehow the first step did not complete properly and some of the binaries had 0 size. 
I re-ran the step1, kept the step1 running while moving on to step2 in a different shell and it worked. 
hope this helps.

**Comment by telegrapher** [comment]
@hellonico , thanks for your help :)
I tried as you said, but it didn't make any difference. 
I'm still investigating the issue.

**Comment by telegrapher** [comment]
I had a deep look at it, and the oracle installed is very buggy.
In my case, the linking of the rman binary was failing, so unless I worked that around, the installation would fail.
I am resorting to manually install oracle inside the container using the graphical installer.
I'll close this issue since it is not related to docker in any way.

**Comment by len-ro** [comment]
I was able to fix the problem by running the runInstaller manually (in a vnc) and when the rman linking failed to apply the patch as described here: http://www.len.ro/work/oracle-12c-on-ubuntu-14-04-sort-of/
